### ISSUE TITLE
Some files are missing

### ISSUE THREAD

**Issue by coolstrong** [jifuwater/linxjourney#1]
Hello, thank you for your cool and simple dots!

It seems that some file are missing - some rofi themes (powermenu, rofidmenu) and scripts (i3/scripts/keyhint-2). Can you please provide them?

**Comment by jifuwater** [comment]
**I'm sorry, the i3 config is a bit messy, but you can delete all the calls to scripts that do not exist. (They are all scripts that I have never used)**

powermenu is integrated in the bar, click the sword icon.
Personally I only use drun for rofi (/rofi/menu-calc.rasi).
I had never used keyhint-2, but the file is [here](https://github.com/endeavouros-team/endeavouros-i3wm-setup/blob/main/etc/skel/.config/i3/scripts/keyhint-2) (not useful in my config).
